
def intro():
    print("A hob goblin is attacking our village!")
    print("Please help us!")
    print("You can choose a class to fight with the goblin.")
    print("Don\'t worry, we've got some special feats for each of your class.")
    print("So first, fighter.")
    print("Fighter is excellent with close-combat and it\'s dealing lots of damage actally.")
    print("You\'ll want to be a fighter when you\'re fighting with a high damage enemy because of its impressive hit points.")
    print("And then, archer.")
    print("Archer has longer attack distance than fighter that makes it fight without getting close with the enemy.")
    print("Archer can sneak into trees and even defeat your enemy without being noticed.")
    print("By the way, archer has more attack movement then other characters.")
    print("Finally, wizard.")
    print("Wizard has the longest attack distance of all.")
    print("And the highest damage and the biggest attack area make it almost impossible to defeat before seeing it.")
    print("But be careful, wizard has low hit points that can be taken down in one hit.")
    print("Good luck dude!")